/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPilotRouteImport } from './routes/admin.pilot'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminProgrammeRouteImport } from './routes/admin.programme'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as ApiNuruSplatRouteImport } from './routes/api/nuru/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPilotRoute = AdminPilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgrammeRoute = AdminProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const ApiNuruSplatRoute = ApiNuruSplatRouteImport.update({
  id: '/api/nuru/$',
  path: '/api/nuru/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/console': typeof ConsoleRoute
  '/developers': typeof DevelopersRoute
  '/impact': typeof ImpactRoute
  '/investors': typeof InvestorsRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/wallet': typeof WalletRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pilot': typeof AdminPilotRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/programme': typeof AdminProgrammeRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/api/nuru/$': typeof ApiNuruSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/developers': typeof DevelopersRoute
  '/impact': typeof ImpactRoute
  '/investors': typeof InvestorsRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/wallet': typeof WalletRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pilot': typeof AdminPilotRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/programme': typeof AdminProgrammeRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin': typeof AdminIndexRoute
  '/api/nuru/$': typeof ApiNuruSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/console': typeof ConsoleRoute
  '/developers': typeof DevelopersRoute
  '/impact': typeof ImpactRoute
  '/investors': typeof InvestorsRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/wallet': typeof WalletRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pilot': typeof AdminPilotRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/programme': typeof AdminProgrammeRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/api/nuru/$': typeof ApiNuruSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/console'
    | '/developers'
    | '/impact'
    | '/investors'
    | '/models'
    | '/pricing'
    | '/sitemap.xml'
    | '/studio'
    | '/wallet'
    | '/admin/contracts'
    | '/admin/knowledge'
    | '/admin/payments'
    | '/admin/pilot'
    | '/admin/pricing'
    | '/admin/programme'
    | '/admin/support'
    | '/admin/'
    | '/api/nuru/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/developers'
    | '/impact'
    | '/investors'
    | '/models'
    | '/pricing'
    | '/sitemap.xml'
    | '/studio'
    | '/wallet'
    | '/admin/contracts'
    | '/admin/knowledge'
    | '/admin/payments'
    | '/admin/pilot'
    | '/admin/pricing'
    | '/admin/programme'
    | '/admin/support'
    | '/admin'
    | '/api/nuru/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/console'
    | '/developers'
    | '/impact'
    | '/investors'
    | '/models'
    | '/pricing'
    | '/sitemap.xml'
    | '/studio'
    | '/wallet'
    | '/admin/contracts'
    | '/admin/knowledge'
    | '/admin/payments'
    | '/admin/pilot'
    | '/admin/pricing'
    | '/admin/programme'
    | '/admin/support'
    | '/admin/'
    | '/api/nuru/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConsoleRoute: typeof ConsoleRoute
  DevelopersRoute: typeof DevelopersRoute
  ImpactRoute: typeof ImpactRoute
  InvestorsRoute: typeof InvestorsRoute
  ModelsRoute: typeof ModelsRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  WalletRoute: typeof WalletRoute
  ApiNuruSplatRoute: typeof ApiNuruSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pilot': {
      id: '/admin/pilot'
      path: '/pilot'
      fullPath: '/admin/pilot'
      preLoaderRoute: typeof AdminPilotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programme': {
      id: '/admin/programme'
      path: '/programme'
      fullPath: '/admin/programme'
      preLoaderRoute: typeof AdminProgrammeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/nuru/$': {
      id: '/api/nuru/$'
      path: '/api/nuru/$'
      fullPath: '/api/nuru/$'
      preLoaderRoute: typeof ApiNuruSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminContractsRoute: typeof AdminContractsRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPilotRoute: typeof AdminPilotRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProgrammeRoute: typeof AdminProgrammeRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContractsRoute: AdminContractsRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPilotRoute: AdminPilotRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProgrammeRoute: AdminProgrammeRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConsoleRoute: ConsoleRoute,
  DevelopersRoute: DevelopersRoute,
  ImpactRoute: ImpactRoute,
  InvestorsRoute: InvestorsRoute,
  ModelsRoute: ModelsRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  WalletRoute: WalletRoute,
  ApiNuruSplatRoute: ApiNuruSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
